INSERT INTO clientes(nombre, direccion, horarios, localidad, particular) VALUES
('Market', 'Juana Manso 435', '8:00 a 00:00', 'CABA', FALSE),
('Dud', 'Olga Cossettini 1150', '8:00 a 00:00', 'CABA', FALSE),
('Zen', 'Vera Peñaloza 400', '8:00 a 00:00', 'CABA', FALSE),
('Wi 5', 'Aime Paine 1559', '8:30 a 22:00', 'CABA', FALSE),
('Ok Food', 'Encarnación Ezcurra 357', '9:00 a 22:00', 'CABA', FALSE),
('Drugstore', 'Bouchard 474', NULL, 'CABA', FALSE),
('Caffe del Doge', 'Manuel Ugarte 2384', '8:00 a 20:00', 'CABA', FALSE),
('Shell Bosque', 'Av La Plata 3601', '24/7', 'Quilmes', FALSE),
('Shell Jumbo', 'Av Calchaqui y Craviotto', '24/7', 'Quilmes', FALSE),
('Cositas Ricas', 'Moreno 685', '9:00 a 19:30', 'Quilmes', FALSE),
('Alsina', 'Alem 248', '8:30 a 20:00', 'Quilmes', FALSE),
('Lusitano', 'Av Eva Peron 2928', '8:30 a 21:00', 'Berazategui', FALSE),
('Club del Jamon', 'Calle 14 2479', '9:00 a 14:30 // 17:00 a 22:00', 'Berazategui', FALSE),
('Sabino','' , '', 'Berazategui' , TRUE),
('Polleria Los Tanos (Fernanda)','Av 17 de Octubre y Calle 700' , '9:00 a 23:00', 'Ciudad Evita' , FALSE),
('Easy Food','Del Valle Iberlucea 2966' , '9:00 a 19:30', 'Lanus' , FALSE),
('Naturaleza Viva','Av La Plata 402' , '9:00 a 19:00', 'Varela' , FALSE),
('Roxana (Luvianka)','Warnes 1416 y Av San Martin' , '24/7', 'Lanus' , FALSE),
('Claudia','Tres Sargentos' , '', 'CABA' , FALSE),
('Patricia','' , '', 'Pilar' , FALSE),
('Flavia','Molina Massey 3332' , '', 'Longchamps' , FALSE),
('Break','Leiva 4006' , '10:00 a 18:00', 'CABA' , FALSE),
('Gym', 'Av Calchaqui 2089', '7:00 a 22:00', 'Quilmes', FALSE),
('La Mariposa', 'Belgrano 902', '', 'Avellaneda', FALSE),
('Giselle', 'Agustin de Benedetti 2100', '8:00 a 19:00', 'Dock Sud', FALSE),
('Medialunas del abuelo', 'Humboldt 2266', '7:00 a 19:00', 'CABA', FALSE),
('Digna Quintana', 'Av Prefectura Naval 800', '9:00 a 17:00', 'CABA', FALSE),
('Via Saludable', 'Av Mitre 3335', '9:30 a 13:30 // 17:00 a 20:00', 'Sarandi', FALSE),
('Supermarket 58', 'Av Mariano Castex 3223', '8:30 a 20:30', 'Canning', FALSE),
('RyB', 'Juana Manso 1133', '9:00 a 3:00', 'CABA', FALSE),
('Coco', 'Combate de los Pozos 1770', '8:00 a 20:00', 'Parque Patricios', FALSE),
('Super Aora', 'Coronel Rosales 1755', '9:00 a 13:00 // 17:00 a 20:30', 'Remedios de Escalada', FALSE),
('Petit', 'Jose Maria Bosch 1424', '6:00 a 20:00', 'Villa Bosch', FALSE),
('Ateri', 'Nuestra señora de Loreto 2394', '6:00 a 20:00', 'Villa Raffo', FALSE),
('San Antonio', 'Santo Vega 7393', '6:00 a 00:00', 'Villa Bosch', FALSE),
('Graciela', 'Av Costanera entre 104 y 106', '9:30 a 00:00', 'Punta Lara', FALSE),
('Heliconias', 'Yapeyu 309 esquina Belgrano', '8:00 a 20:00', 'Almagro', FALSE),
('Daniel', 'Calle 156 6097', '9:00 a 13:00 // 17:00 a 21:00', 'Hudson', FALSE),
('Diamela', 'Ramon Franco 1135', '24/7', 'Lomas', FALSE),
('Proveeduria', 'Calle 22 896 esquina 17', '9:00 a 20:00', 'Varela', FALSE),
('Ginkgo', 'Esmeralda 587', '7:00 a 20:00', 'CABA', FALSE),
('German', 'Ruta 2 km 38', '24/7', 'El Pato', FALSE),
('Lo de Vane', 'Calle 149 entre 7 y 8', '9:00 a 21:00', 'Berazategui', FALSE),
('Silvana', 'Corrientes 2466', '24/7', 'Quilmes', FALSE);

INSERT INTO productos(nombre, categoria, alias_facturacion, precio) VALUES
-- TARTAS MASA BLANCA (5.140)
('Tarta de Jamón y Queso (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Calabaza (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Pollo (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Verdura (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Brócoli (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Jamón y Puerro (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Queso y Cebolla (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Zapallito (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta de Choclo (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta Bicolor (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),
('Tarta Capresse (Blanca)', 'Tartas', 'Tarta Masa Blanca', 5140.00),

-- TARTAS MASA INTEGRAL (5.140)
('Tarta Jamón y Queso (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Calabaza (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Pollo (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Verdura (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Brócoli (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Jamón y Puerro (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Queso y Cebolla (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Zapallito (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta de Choclo (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta Bicolor (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),
('Tarta Capresse (Integral)', 'Tartas', 'Tarta Masa Integral', 5140.00),

-- ENSALADAS SIN ADEREZO (6.675 / 7.675)
('Ensalada Caesar (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Chef (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Sureña (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Natural (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Vegetariana (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Veggie (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Yamani (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Tuna (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada Col (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 6675.00),
('Ensalada YouFood (s/a)', 'Ensaladas', 'Ensalada s/ Aderezo', 7325.00),
('Ensalada Italiana (s/a)', 'Ensaladas', 'Ensalada Premium s/a', 7675.00),
('Ensalada de Queso Azul (s/a)', 'Ensaladas', 'Ensalada Premium s/a', 7675.00),

-- ENSALADAS CON ADEREZO (7.325 / 8.395)
('Ensalada Caesar (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Chef (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Sureña (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Natural (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Vegetariana (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Veggie (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Yamani (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Tuna (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Col (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada YouFood (c/a)', 'Ensaladas', 'Ensalada c/ Aderezo', 7325.00),
('Ensalada Italiana (c/a)', 'Ensaladas', 'Ensalada Premium c/a', 8395.00),
('Ensalada de Queso Azul (c/a)', 'Ensaladas', 'Ensalada Premium c/a', 8395.00),

-- EMPANADAS X UNIDAD (1.475)
('Empanada de Carne a Cuchillo', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Carne Suave', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Pollo', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Jamón y Queso', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Calabaza', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Verdura', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Choclo', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada de Queso y Cebolla', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada Vegana', 'Empanadas', 'Empanada x Unidad', 1475.00),
('Empanada Capresse', 'Empanadas', 'Empanada x Unidad', 1475.00),

-- EMPANADAS X UNIDAD INTEGRAL (1.475)
('Empanada de Carne a Cuchillo (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Carne Suave (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Pollo (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Jamón y Queso (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Calabaza (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Verdura (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Choclo (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada de Queso y Cebolla (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada Vegana (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),
('Empanada Capresse (Integral)', 'Empanadas', 'Empanada x Unidad Integral', 1475.00),

-- EMPANADAS X3 (3.805)
('Pack 3 Empanadas de Carne a Cuchillo', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Carne Suave', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Pollo', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Jamón y Queso', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Calabaza', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Verdura', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Choclo', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas de Queso y Cebolla', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas Vegana', 'Empanadas', 'Empanada x3', 3805.00),
('Pack 3 Empanadas Capresse', 'Empanadas', 'Empanada x3', 3805.00),

-- EMPANADAS X3 INTEGRAL
('Pack 3 Empanadas de Carne a Cuchillo (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Carne Suave (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Pollo (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Jamón y Queso (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Calabaza (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Verdura (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Choclo (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas de Queso y Cebolla (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas Vegana (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),
('Pack 3 Empanadas Capresse (Integral)', 'Empanadas', 'Empanada x3 Integral', 3805.00),

-- EMPANADAS X12 (15.105)
('Docena de Empanadas de Carne a Cuchillo', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Carne Suave', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Pollo', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Jamón y Queso', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Calabaza', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Verdura', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Choclo', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas de Queso y Cebolla', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas Veganas', 'Empanadas', 'Empanada x12', 15105.00),
('Docena de Empanadas Capresse', 'Empanadas', 'Empanada x12', 15105.00),

--EMPANADAS X12 INTEGRAL
('Docena de Empanadas de Carne a Cuchillo (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Carne Suave (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Pollo (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Jamón y Queso (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Calabaza (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Verdura (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Choclo (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas de Queso y Cebolla (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas Veganas (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),
('Docena de Empanadas Capresse (Integral)', 'Empanadas', 'Empanada x12 Integral', 15105.00),

-- VIANDAS (8.130)
('Spaghetti con Panache de vegetales', 'Viandas', 'Viandas', 8130.00),
('Chop Suey con Arroz y Pollo', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Berenjena Napolitana con Vegetales', 'Viandas', 'Viandas', 8130.00),
('Risotto de Pollo y Puerro', 'Viandas', 'Viandas', 8130.00),
('Mila de Soja Capresse con Pure Calabaza', 'Viandas', 'Viandas', 8130.00),
('Spaguetis con Crema Espinaca', 'Viandas', 'Viandas', 8130.00),
('Lasagna de Vegetales con Fileto', 'Viandas', 'Viandas', 8130.00),
('Tortilla de Espinaca con Zanahorias', 'Viandas', 'Viandas', 8130.00),
('Hamburguesa Veggie con Arroz', 'Viandas', 'Viandas', 8130.00),
('Pollo Grillado con arroz Primavera', 'Viandas', 'Viandas', 8130.00),
('Calabaza Rellena Gratinada', 'Viandas', 'Viandas', 8130.00),
('Pollo Grillado con Vegetales', 'Viandas', 'Viandas', 8130.00),
('Canelones de Calabaza con Salsa Rosa', 'Viandas', 'Viandas', 8130.00),
('Pechuguitas rebozadas con Revuelto de Zapallitos', 'Viandas', 'Viandas', 8130.00),
('Tortilla de Zapallito con Zanahorias', 'Viandas', 'Viandas', 8130.00),
('Pollo Relleno al Verdeo con Papas', 'Viandas', 'Viandas', 8130.00),
('Bondiola al Verdeo con Batatas', 'Viandas', 'Viandas', 8130.00),
('Omelette de Jamón y Queso con Papas', 'Viandas', 'Viandas', 8130.00),
('Tortilla de Zanahoria con Brócoli', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Calabaza con arroz Yamaní', 'Viandas', 'Viandas', 8130.00),
('Canelones de Ricota y Jamón', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Pollo Napolitana con Puré', 'Viandas', 'Viandas', 8130.00),
('Bondiola a la Mostaza con Puré', 'Viandas', 'Viandas', 8130.00),
('Crepe de Pollo con Salsa de Queso', 'Viandas', 'Viandas', 8130.00),
('Pollo a la Mostaza con Puré', 'Viandas', 'Viandas', 8130.00),
('Guiso de Lentejas', 'Viandas', 'Viandas', 8130.00),
('Lasagna de Espinaca con Bolognesa', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Pollo a la Fugazzeta con Papas', 'Viandas', 'Viandas', 8130.00),
('Wok de Pollo con Vegetales', 'Viandas', 'Viandas', 8130.00),
('Wok de Cerdo con Arroz', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Berenjena a la Fugazzeta', 'Viandas', 'Viandas', 8130.00),
('Fajitas de Ternera al Verdeo con Puré', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Pollo a la Suiza con Papas', 'Viandas', 'Viandas', 8130.00),
('Tallarines con Brócoli y Cherry', 'Viandas', 'Viandas', 8130.00),
('Pechuguita Capresse Papa Batata', 'Viandas', 'Viandas', 8130.00),
('Chow Mien Vegetariano', 'Viandas', 'Viandas', 8130.00),
('Wok Veggie con Lentejas', 'Viandas', 'Viandas', 8130.00),
('Brochette de Cerdo BBQ', 'Viandas', 'Viandas', 8130.00),
('Milanesa de Soja Napolitana con Arroz', 'Viandas', 'Viandas', 8130.00),
('Crepe de Calabaza y Choclo con Bechamel', 'Viandas', 'Viandas', 8130.00),
('Ternera al Verdeo con Puré', 'Viandas', 'Viandas', 8130.00),
('Albóndigas con Cheddar y Papas', 'Viandas', 'Viandas', 8130.00),
('Ravioles de Ricota con Crema Calabaza', 'Viandas', 'Viandas', 8130.00),
('Pastel de Pollo y Calabaza', 'Viandas', 'Viandas', 8130.00),
('Omelette de Verduras con Calabazas', 'Viandas', 'Viandas', 8130.00),
('Risotto de Vegetales', 'Viandas', 'Viandas', 8130.00),
('Pollo Grillado con Espinaca a la Crema', 'Viandas', 'Viandas', 8130.00),
('Pollo Portuguesa con Arroz', 'Viandas', 'Viandas', 8130.00),
('Ravioles con Fileto y  Albahaca', 'Viandas', 'Viandas', 8130.00),
('Fideos Tricolor con Estofado', 'Viandas', 'Viandas', 8130.00),
('Bondiola BBQ con Batatas', 'Viandas', 'Viandas', 8130.00),
('Pastel de Papas con Queso', 'Viandas', 'Viandas', 8130.00),

-- WRAPS (6.195 / 6.880 / 5.070)
('Wrap de Jamón y Queso', 'Wraps', 'Wrap Clásico', 6195.00),
('Wrap Caesar', 'Wraps', 'Wrap Clásico', 6195.00),
('Wrap de Carne', 'Wraps', 'Wrap de Carne', 6880.00),
('Wrap Vegetariano', 'Wraps', 'Wrap Veggie', 5070.00),
('Wrap Integral de Jamón y Queso', 'Wraps', 'Wrap Clásico Integral', 6195.00),
('Wrap Integral Caesar', 'Wraps', 'Wrap Clásico Integral', 6195.00),
('Wrap Integral de Carne', 'Wraps', 'Wrap de Carne Integral', 6880.00),
('Wrap Integral Vegetariano', 'Wraps', 'Wrap Veggie Integral', 5070.00),

-- BURRITOS Y ROLLS (Rolls van a Burritos por pedido)
('Burrito Pollo', 'Burritos', 'Burrito', 7560.00),
('Burrito Carne', 'Burritos', 'Burrito', 7560.00),
('Roll Tropical', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Espinaca', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Halloween', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Zapallitos', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Cheese', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Orions', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Red', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Green', 'Burritos', 'Roll Vegano', 5085.00),
('Roll Oriental', 'Burritos', 'Roll Vegano', 5085.00),

-- PIZZAS
('Pizzetón Individual de Muzzarella', 'Pizzas', 'Pizzetón', 5170.00),
('Pizza Grande de Muzzarella', 'Pizzas', 'Pizza Grande', 7815.00),
('Pizza lista de Muzzarella', 'Pizzas', 'Pizza Lista', 5720.00),
('Pizza lista de Cebolla', 'Pizzas', 'Pizza Lista', 5720.00),
('Pizza lista de Calabresa', 'Pizzas', 'Pizza Especial', 6740.00),
('Pizza lista de Roquefort', 'Pizzas', 'Pizza Especial', 6740.00),
('Pizza lista de Jamón', 'Pizzas', 'Pizza Especial', 6740.00),
('Pizza lista de Jamón y morrón', 'Pizzas', 'Pizza Especial', 6740.00),

-- PANINIS (Normal / Salvado / Vegano)
('Panini de Ternera', 'Paninis', 'Panini de Ternera Cheddar', 5585.00),
('Panini de Bondiola', 'Paninis', 'Panini de Bondiola', 5585.00),
('Panini de Pollo', 'Paninis', 'Panini de Pollo', 5585.00),
('Panini de Jamón y Queso', 'Paninis', 'Panini de Jamón y Queso', 3990.00),
('Panini de Salame y Queso', 'Paninis', 'Panini de Salame y Queso', 3990.00),
('Panini de Crudo y Queso', 'Paninis', 'Panini de Crudo y Queso', 4410.00),
('Panini de Lomito y Cheddar', 'Paninis', 'Panini de Lomito y Cheddar', 5465.00),
('Panini de Bondiola y Cebolla', 'Paninis', 'Panini de Bondiola y Cebolla', 5715.00),
('Panini de Carne y Cebolla', 'Paninis', 'Panini de Carne y Cebolla', 5715.00),
('Panini de Salvado de Ternera', 'Paninis', 'Panini de Salvado de Ternera', 6160.00),
('Panini de Salvado de Bondiola', 'Paninis', 'Panini de Salvado de Bondiola', 6160.00),
('Panini de Salvado de Pollo', 'Paninis', 'Panini de Salvado de Pollo Verdeo', 6160.00),
('Panini de Salvado de Jamón y Queso', 'Paninis', 'Panini de Salvado Jamón Queso', 4500.00),
('Panini de Salvado de Salame y Queso', 'Paninis', 'Panini de Salvado Jamón Queso', 4500.00),
('Panini de Salvado de Crudo y Queso', 'Paninis', 'Panini de Salvado Crudo Queso', 5140.00),
('Panini de Salvado de Lomito Cheddar', 'Paninis', 'Panini de Salvado Lomito Cheddar', 6160.00),
('Panini de Salvado de Bondiola y Cebolla', 'Paninis', 'Panini de Salvado de Bondiola y Cebolla', 6365.00),
('Panini de Salvado de Carne y Cebolla', 'Paninis', 'Panini de Salvado de Carne y Cebolla', 6365.00),
('Panini Vegano Red', 'Paninis', 'Panini Vegano', 5085.00),
('Panini Vegano Green', 'Paninis', 'Panini Vegano', 5085.00),
('Panini Vegano Orions', 'Paninis', 'Panini Vegano', 5085.00),
('Panini Vegano Oriental', 'Paninis', 'Panini Vegano', 5085.00),
('Panini Vegano Italiana', 'Paninis', 'Panini Vegano', 5085.00),

-- SÁNDWICHES
('Árabe de Jamón y Queso', 'Sándwiches', 'Sandwich Árabe/Pebete', 4230.00),
('Árabe de Salame y Queso', 'Sándwiches', 'Sandwich Árabe/Pebete', 3710.00),
('Pebete de Jamón y Queso', 'Sándwiches', 'Sandwich Árabe/Pebete', 4230.00),
('Pebete de Salame y Queso', 'Sándwiches', 'Sandwich Árabe/Pebete', 4230.00),
('Sándwich de Milanesa de Carne', 'Sándwiches', 'Sandwich de Milanesa', 5465.00),
('Sándwich de Milanesa de Pollo', 'Sándwiches', 'Sandwich de Milanesa', 5465.00),
('Triples de Miga (Unidad)', 'Sándwiches', 'Sandwich de Miga', 1425.00),
('Triples de Miga (x3)', 'Sándwiches', 'Sandwich de Miga x3', 4230.00),
('Triples de Miga (x6)', 'Sándwiches', 'Sandwich de Miga x6', 8430.00),
('Tostados de Jamón y Queso x32', 'Sándwiches', 'Tostados x32', 41150.00),

-- OTROS
('Ensalada de Fruta', 'Otros', 'Ensalada de Fruta', 4735.00),
('Medialunas de Jamón y Queso x2', 'Otros', 'Medialunas x2', 3315.00),
('Medialunas de Jamón y Queso x12', 'Otros', 'Medialunas x12', 28575.00),
('Pollo Cocido por Kilo', 'Otros', 'Pollo Cocido x Kilo', 18370.00);

INSERT INTO empleados(nombre, sector, sueldo) VALUES
('Jonás', 'Administración', 80000.00),
('Lautaro', 'Administración', 80000.00),
('Macarena', 'Administración', 0),
('Facundo', 'Ensaladas', 150000.00),
('Sofía', 'Ensaladas', 0),
('Carla', 'Ensaladas', 0),
('Pacha', 'Cocina', 0),
('Natalia', 'Cocina', 0),
('Lorena', 'Cocina', 0),
('Fernando', 'Cocina', 0),
('Valeria', 'Empanadas', 0),
('Noelia', 'Empanadas', 0),
('Paula', 'Empanadas', 0),
('Gustavo', 'Reparto', 0),
('Ezequiel', 'Reparto', 0),
('Tomás', 'Reparto', 0),
('Matías', 'Panadería', 0),
('Joaquin', 'Otros', 0),
('Miguel', 'Ventas', 110000.00);
